// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as WalletContainer from "./WalletContainer.mjs";

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement("div", undefined, React.createElement(WalletContainer.make, {})), root);
}

export {
  
}
/* root Not a pure module */
