// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.mjs";
import * as React from "react";
import * as ReactDom from "react-dom";

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement("div", undefined, React.createElement(Test.make, {})), root);
}

export {
  
}
/* root Not a pure module */
