// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_array from "../node_modules/rescript/lib/es6/caml_array.js";

import {ethers} from 'ethers'
;

function getAccountBalanceP(account) {
  return window.ethereum.request({
              method: "eth_getBalance",
              params: [
                Caml_array.get(account, 0),
                "latest"
              ]
            });
}

function connectToMetamaskWalletP(param) {
  return window.ethereum.request({
              method: "eth_requestAccounts"
            });
}

function submitTransactionP(amountInEth, toAddress) {
  var provider = new ethers.providers.Web3Provider(window.ethereum);
  var signer = provider.getSigner();
  return signer.sendTransaction({
              to: toAddress,
              value: ethers.utils.parseEther(amountInEth)
            });
}

export {
  getAccountBalanceP ,
  connectToMetamaskWalletP ,
  submitTransactionP ,
  
}
/*  Not a pure module */
