// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_array from "../node_modules/rescript/lib/es6/caml_array.js";
import * as Belt_Option from "../node_modules/rescript/lib/es6/belt_Option.js";

import {ethers} from 'ethers';
;

function MetamaskTest(Props) {
  var match = React.useState(function () {
        return [""];
      });
  var setMetamaskAddress = match[1];
  var match$1 = React.useState(function () {
        
      });
  var handlers = {
    connectToMetamaskWallet: (function (param) {
        window.ethereum.request({
                method: "eth_requestAccounts"
              }).then(function (acc) {
              console.log("Acc value fetched after promise: ", acc);
              Curry._1(setMetamaskAddress, (function (param) {
                      return [acc];
                    }));
              window.ethereum.request({
                      method: "eth_getBalance",
                      params: [
                        [acc],
                        ["latest"]
                      ]
                    }).then(function (someBal) {
                    console.log("Somebalance fetched is: ", someBal);
                    return Promise.resolve(undefined);
                  });
              return Promise.resolve({
                          method: "eth_requestAccounts"
                        });
            });
        
      })
  };
  return React.createElement("div", undefined, React.createElement("p", {
                  className: "p-5 text-3xl"
                }, "Welcome to Metamask test"), React.createElement("div", {
                  className: "p-5"
                }, React.createElement("button", {
                      className: "p-5 bg-blue-400 rounded-lg text-white",
                      onClick: handlers.connectToMetamaskWallet
                    }, "Connect to Metamask")), React.createElement("div", {
                  className: "p-5 text-3xl "
                }, React.createElement("p", undefined, "Account address: ", Caml_array.get(match[0], 0)), React.createElement("p", undefined, "Account balance: ", Belt_Option.getWithDefault(match$1[0], "value not available(Metamask not connected)"))));
}

var make = MetamaskTest;

export {
  make ,
  
}
/*  Not a pure module */
