// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var win = window.ethereum;

console.log("Connected to metamsk wallet: ", window.ethereum.request({
          method: "eth_requestAccounts"
        }));

function MetamaskTest(Props) {
  return React.createElement("div", undefined, React.createElement("p", {
                  className: "p-5 text-3xl"
                }, "Welcome to Metamask test"), React.createElement("p", {
                  className: "p-5 text-3xl"
                }, "Hello"));
}

var make = MetamaskTest;

export {
  win ,
  make ,
  
}
/* win Not a pure module */
