// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "../node_modules/rescript/lib/es6/belt_Option.js";

function reducer(state, action) {
  return state;
}

function TransactionContainer(Props) {
  var match = React.useReducer(reducer, {
        toAddress: undefined,
        amount: undefined
      });
  var state = match[0];
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "p-4"
                }, React.createElement("p", {
                      className: "mb-7"
                    }, "Send ethereum:"), React.createElement("input", {
                      className: "p-5 w-7/12 ring-2 ring-blue-400",
                      placeholder: "To address..",
                      type: "text",
                      value: Belt_Option.getWithDefault(state.toAddress, "")
                    }), React.createElement("input", {
                      className: "mt-7 p-5 w-7/12 ring-2 ring-blue-400",
                      placeholder: "Amount..",
                      type: "text",
                      value: String(Belt_Option.getWithDefault(state.amount, 0.0))
                    }), React.createElement("div", {
                      className: "mt-5"
                    }, React.createElement("button", {
                          className: "p-3 bg-blue-400  text-xl rounded-lg text-white"
                        }, "Submit"))));
}

var make = TransactionContainer;

export {
  reducer ,
  make ,
  
}
/* react Not a pure module */
