// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function TransactionSuccess(Props) {
  var txResponse = Props.txResponse;
  var classes = "mt-5 border border-green-500 bg-green-200 rounded-md p-5";
  if (txResponse !== undefined) {
    return React.createElement("div", {
                className: classes
              }, React.createElement("p", undefined, "Transaction successful"), React.createElement("p", undefined, "Transaction ID: ", txResponse.hash));
  } else {
    return React.createElement("p", {
                className: classes
              }, "Transaction Failed ");
  }
}

var make = TransactionSuccess;

export {
  make ,
  
}
/* react Not a pure module */
