// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Option from "../node_modules/rescript/lib/es6/belt_Option.js";

function reducer(state, action) {
  if (action.TAG === /* SetToAddress */0) {
    return {
            toAddress: action._0,
            amount: state.amount
          };
  } else {
    return {
            toAddress: state.toAddress,
            amount: action._0
          };
  }
}

function TransactionContainer(Props) {
  var match = React.useReducer(reducer, {
        toAddress: undefined,
        amount: undefined
      });
  var dispatch = match[1];
  var state = match[0];
  var handlers_updateToAddress = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    return Curry._1(dispatch, {
                TAG: /* SetToAddress */0,
                _0: value
              });
  };
  var handlers_updateAmount = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    return Curry._1(dispatch, {
                TAG: /* SetAmount */1,
                _0: value
              });
  };
  var handlers_handleSubmit = function (param) {
    console.log("from inside handle submit, amount is: ", state.amount);
    
  };
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "p-4"
                }, React.createElement("p", {
                      className: "mb-7"
                    }, "Send ethereum:"), React.createElement("input", {
                      className: "p-5 w-7/12 ring-2 ring-blue-400",
                      placeholder: "To address..",
                      type: "text",
                      value: Belt_Option.getWithDefault(state.toAddress, ""),
                      onChange: handlers_updateToAddress
                    }), React.createElement("input", {
                      className: "mt-7 p-5 w-7/12 ring-2 ring-blue-400",
                      placeholder: "Amount..",
                      type: "text",
                      value: String(Belt_Option.getWithDefault(state.amount, 0.0)),
                      onChange: handlers_updateAmount
                    }), React.createElement("div", {
                      className: "mt-5"
                    }, React.createElement("button", {
                          className: "p-3 bg-blue-400  text-xl rounded-lg text-white",
                          onClick: handlers_handleSubmit
                        }, "Submit"))));
}

var make = TransactionContainer;

export {
  reducer ,
  make ,
  
}
/* react Not a pure module */
